/*
 * This file is generated by jOOQ.
 */
package com.project.recipes.adapter.repository.jooq.tables;


import com.project.recipes.adapter.repository.jooq.DefaultSchema;
import com.project.recipes.adapter.repository.jooq.Indexes;
import com.project.recipes.adapter.repository.jooq.tables.records.PreparationMethodRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PreparationMethod extends TableImpl<PreparationMethodRecord> {

    private static final long serialVersionUID = -91423104;

    /**
     * The reference instance of <code>preparation_method</code>
     */
    public static final PreparationMethod PREPARATION_METHOD = new PreparationMethod();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PreparationMethodRecord> getRecordType() {
        return PreparationMethodRecord.class;
    }

    /**
     * The column <code>preparation_method.ID</code>.
     */
    public final TableField<PreparationMethodRecord, Long> ID = createField("ID", org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>preparation_method.METHOD</code>.
     */
    public final TableField<PreparationMethodRecord, String> METHOD = createField("METHOD", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * Create a <code>preparation_method</code> table reference
     */
    public PreparationMethod() {
        this(DSL.name("preparation_method"), null);
    }

    /**
     * Create an aliased <code>preparation_method</code> table reference
     */
    public PreparationMethod(String alias) {
        this(DSL.name(alias), PREPARATION_METHOD);
    }

    /**
     * Create an aliased <code>preparation_method</code> table reference
     */
    public PreparationMethod(Name alias) {
        this(alias, PREPARATION_METHOD);
    }

    private PreparationMethod(Name alias, Table<PreparationMethodRecord> aliased) {
        this(alias, aliased, null);
    }

    private PreparationMethod(Name alias, Table<PreparationMethodRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PREPARATION_METHOD_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<PreparationMethodRecord, Long> getIdentity() {
        return Internal.createIdentity(com.project.recipes.adapter.repository.jooq.tables.PreparationMethod.PREPARATION_METHOD, com.project.recipes.adapter.repository.jooq.tables.PreparationMethod.PREPARATION_METHOD.ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<PreparationMethodRecord> getPrimaryKey() {
        return Internal.createUniqueKey(com.project.recipes.adapter.repository.jooq.tables.PreparationMethod.PREPARATION_METHOD, "KEY_preparation_method_PRIMARY", com.project.recipes.adapter.repository.jooq.tables.PreparationMethod.PREPARATION_METHOD.ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<PreparationMethodRecord>> getKeys() {
        return Arrays.<UniqueKey<PreparationMethodRecord>>asList(
              Internal.createUniqueKey(com.project.recipes.adapter.repository.jooq.tables.PreparationMethod.PREPARATION_METHOD, "KEY_preparation_method_PRIMARY", com.project.recipes.adapter.repository.jooq.tables.PreparationMethod.PREPARATION_METHOD.ID)
        );
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PreparationMethod as(String alias) {
        return new PreparationMethod(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PreparationMethod as(Name alias) {
        return new PreparationMethod(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public PreparationMethod rename(String name) {
        return new PreparationMethod(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PreparationMethod rename(Name name) {
        return new PreparationMethod(name, null);
    }
}
