CREATE TABLE recipes (
  ID BIGINT(19) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(255) NOT NULL,
  INGREDIENTS VARCHAR(255) NOT NULL,
  PREPARATION_METHOD VARCHAR(255) NOT NULL,
  CATEGORY VARCHAR(255) NOT NULL
);