/*
 * This file is generated by jOOQ.
 */
package com.project.recipes.adapter.repository.jooq;


import com.project.recipes.adapter.repository.jooq.tables.Category;
import com.project.recipes.adapter.repository.jooq.tables.Ingredients;
import com.project.recipes.adapter.repository.jooq.tables.PreparationMethod;
import com.project.recipes.adapter.repository.jooq.tables.Recipes;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code></code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index CATEGORY_PRIMARY = Indexes0.CATEGORY_PRIMARY;
    public static final Index INGREDIENTS_PRIMARY = Indexes0.INGREDIENTS_PRIMARY;
    public static final Index PREPARATION_METHOD_PRIMARY = Indexes0.PREPARATION_METHOD_PRIMARY;
    public static final Index RECIPES_PRIMARY = Indexes0.RECIPES_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index CATEGORY_PRIMARY = Internal.createIndex("PRIMARY", Category.CATEGORY, new OrderField[] { Category.CATEGORY.ID }, true);
        public static Index INGREDIENTS_PRIMARY = Internal.createIndex("PRIMARY", Ingredients.INGREDIENTS, new OrderField[] { Ingredients.INGREDIENTS.ID }, true);
        public static Index PREPARATION_METHOD_PRIMARY = Internal.createIndex("PRIMARY", PreparationMethod.PREPARATION_METHOD, new OrderField[] { PreparationMethod.PREPARATION_METHOD.ID }, true);
        public static Index RECIPES_PRIMARY = Internal.createIndex("PRIMARY", Recipes.RECIPES, new OrderField[] { Recipes.RECIPES.ID }, true);
    }
}
